---
title: 'ECON312 Problem Set 1: question 2e'
author: Futing Chen, Will Parker
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_notebook:
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, warning = FALSE, message = FALSE)
```

```{r, cache = FALSE}
library(tidyverse)
library(knitr)
```


\pagebreak

# Roy model simulator function

```{r}
roy_model <- function(sigma, rho, N = 10000, means = c(0,0), seed = 12346){
  set.seed(seed)
  cov_matrix <- matrix(c(sigma^2, rho*sigma, rho*sigma, 1), nrow = 2)
  
  sample <- mvtnorm::rmvnorm(n = N, means, cov_matrix) 
  
  colnames(sample) <- c("U1", "U0")
  
  sample <- as_tibble(sample) %>%
    mutate(D = ifelse(U1 > U0, 1, 0),
           beta = U1-U0,
           Y = D*U1 + (1-D)*U0)
  
  ATE <- sample$beta %>% mean()
  
  ATT <- filter(sample, D ==1)$beta %>% mean()
  
  ATUT <- filter(sample, D == 0)$beta %>% mean()
  
  # beta OLS
  model <- lm(Y ~ D, data = sample)
  
  beta_OLS <- model$coefficients[2]
  
  E_Y_D1 = filter(sample, D ==1)$Y %>% mean()
  
  E_Y_D0 = filter(sample, D ==0)$Y %>% mean()
  
  E_diff = E_Y_D1 - E_Y_D0

  
  results <- tibble(
    `quantity of interest` = c("ATE", 
                               "ATT", 
                               "ATUT", 
                               "Beta_OLS",
                               "E[Y|D =1] - E[Y|D =0]"),
    estimate = c(ATE, ATT, ATUT, beta_OLS, E_diff),
    `theoretical result` = c(0, 
                           2*sqrt(sigma^2 + 1 -2*rho*sigma)*dnorm(0),
                           -2*sqrt(sigma^2 + 1 -2*rho*sigma)*dnorm(0),
                           2*dnorm(0)*(sigma^2 - 1)/sqrt(sigma^2 + 1 -2*rho*sigma),
                           2*dnorm(0)*(sigma^2 - 1)/sqrt(sigma^2 + 1 -2*rho*sigma))
  ) %>%
    mutate(estimate = round(estimate, 2),
           `theoretical result` = round(`theoretical result`,2))
  
  kable(results)
}


```


```{r}
plot_treatment_effects <- function(sigma, rho, N = 10000, means = c(0,0), seed = 12346){
  set.seed(seed)
  cov_matrix <- matrix(c(sigma^2, rho*sigma, rho*sigma, 1), nrow = 2)
  
  sample <- mvtnorm::rmvnorm(n = N, means, cov_matrix) 
  
  colnames(sample) <- c("U1", "U0")
  
  sample <- as_tibble(sample) %>%
    mutate(D = ifelse(U1 > U0, 1, 0),
           beta = U1-U0,
           Y = D*U1 + (1-D)*U0)
  
  sample %>%
    ggplot(aes(x = beta, fill = factor(D))) +
    geom_histogram(binwidth = 1, center = 0) +
    ggtitle(paste0("sigma =", sigma, ", rho=", rho)) +
    labs(x = "U1 - U0", fill = "treatment selection")
}
```

\pagebreak

# Simulation results
```{r}
roy_model(2, 0.5)
```

The simulation shows that

$$ E[Y| D= 1] - E[Y|D = 0] = \beta_{OLS} $$



```{r}
roy_model(2, 0)
```

```{r}
roy_model(2, -0.5)
```




# Fixing $\rho= 0.5$ and varying $\sigma$
```{r}
roy_model(1, 0.5)
```

```{r}
roy_model(2, 0.5)
```

```{r}
roy_model(4, 0.5)
```

```{r}
roy_model(10, 0.5)
```



The increase in magnitude of ATT and ATUT as sigma increases can be explained by a larger variance in $U_1 - U_0$ and the $D = \mathbf{1}[U_1 > U_0]$ selection mechanism, as illustrated by these plots
```{r}
plot_treatment_effects(2, 0.5) +
      lims(x = c(-15, 15))
```

```{r}
plot_treatment_effects(4, 0.5) +
      lims(x = c(-15, 15))
```

